name: Test Live Metrics
on:
  workflow_dispatch:
  pull_request:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt

      - uses: iterative/setup-cml@v1
        with:
          version: "0.18.1"

      - name: Train model
        env:
          STUDIO_ENDPOINT: ${{ secrets.STUDIO_ENDPOINT }}
          STUDIO_REPO_URL: ${{ secrets.STUDIO_REPO_URL }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVCLIVE_LOGLEVEL: ${{ secrets.DVCLIVE_LOGLEVEL }}
        run: |
          dvc repro
      - name: CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml pr --rebase "dvc.lock" "params.yaml" "dvclive"
