name: Test Live Metrics
on:
  pull_request:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
      - name: Install
        run: pip install -r requirements.txt
      - name: Train model
        env:
          STUDIO_ENDPOINT: https://dev.iterative.ai/api/live
          STUDIO_REPO_URL: ${{ secrets.STUDIO_REPO_URL }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          DVCLIVE_LOGLEVEL: DEBUG
        run: |
          dvc repro
      - name: CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml pr --rebase "dvc.lock" "params.yaml" "dvclive.json" "dvclive"