name: Model training with Live Metrics in Studio

on:
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: ./.github/workflows/warm_up_caches.yaml
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Train model
        env:
          STUDIO_ENDPOINT: ${{ secrets.STUDIO_ENDPOINT }}
          STUDIO_REPO_URL: ${{ secrets.STUDIO_REPO_URL }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVCLIVE_LOGLEVEL: ${{ secrets.DVCLIVE_LOGLEVEL }}
        run: dvc repro

      - name: Update CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec -- cml pr --rebase "dvc.lock" "params.yaml" "dvclive"
